# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  schedule:
    # Runs "at 00:00 every day" (see https://crontab.guru)
    - cron: '0 1 * * *'
jobs:
  build:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        # Hit the webhook endpoint to rebuild  from the "main" branch
        run: curl -X GET https://barganttic.herokuapp.com/bidding/start
